import type { LlmProvider } from '../providers/types.js'

/**
 * Input passed to each metric's `score()` function.
 *
 * Mirrors one row of the evaluation dataset — all fields come directly from the
 * {@link RagSample} passed to `evaluate()`. The metric implementations receive
 * this object and use whichever fields are relevant to their scoring logic.
 */
export interface MetricInput {
  /** The query that was posed to the RAG pipeline under evaluation. */
  question: string

  /** The answer generated by the RAG pipeline under evaluation. */
  answer: string

  /**
   * The document chunks retrieved by the RAG pipeline and injected into the
   * LLM's prompt. Presented to the judge in numbered order ([Context 1], [Context 2], ...).
   * Ordering matters for contextPrecision scoring.
   */
  contexts: string[]

  /**
   * The expected / reference answer for this question.
   * Only required by `contextRecall` -- other metrics ignore this field.
   * When absent, `contextRecall` returns `skipped: true` for this sample.
   */
  groundTruth?: string
}

/**
 * Output from a single metric evaluation on one sample.
 *
 * Returned by every metric's `score()` method and collected by `evaluate()`
 * into the final {@link EvaluationResult}.
 */
export interface MetricOutput {
  /**
   * The metric score for this sample, in the range [0.0, 1.0].
   * Higher is always better. Scores are clamped to [0, 1] even if the LLM
   * returns values outside that range.
   */
  score: number

  /**
   * The LLM judge's explanation of why it assigned this score.
   * Only populated when `includeReasoning: true` is passed to `evaluate()`.
   * Useful for debugging unexpectedly low or high scores.
   */
  reasoning?: string

  /**
   * When `true`, this metric could not be computed for this sample and should
   * be excluded from all aggregates. The most common cause is `contextRecall`
   * being evaluated on a sample without a `groundTruth` field.
   *
   * `evaluate()` detects `skipped: true` and omits the score from both
   * per-sample `scores` and the per-metric aggregate -- it is never counted
   * as a 0. This prevents silent score distortion.
   *
   * The `score` field is still set to 0 for backward compatibility with code
   * that reads raw MetricOutput without checking `skipped`.
   */
  skipped?: boolean
}

/**
 * A Metric is a named evaluation function that scores a single RAG sample.
 *
 * All five built-in metrics implement this interface. You can also implement
 * it yourself to create custom domain-specific metrics -- any string name is
 * accepted, not just the five built-in names:
 *
 * @example
 * ```typescript
 * import type { Metric, MetricInput, MetricOutput } from 'rageval'
 * import { jsonInstruction, parseLlmScore } from 'rageval'
 *
 * // Custom metric with a domain-specific name — any string is valid
 * const sourceAttribution: Metric = {
 *   name: 'sourceAttribution',
 *   description: 'Checks whether the answer cites sources from the context.',
 *   async score(input, provider, includeReasoning = false) {
 *     const prompt = `Evaluate whether the answer cites sources.
 *
 * CONTEXT: ${input.contexts.join('\n')}
 * ANSWER: ${input.answer}
 *
 * ${jsonInstruction(includeReasoning)}`
 *     const response = await provider.complete(prompt)
 *     const { score, reasoning } = parseLlmScore(response)
 *     return { score, ...(includeReasoning && { reasoning }) }
 *   },
 * }
 * ```
 */
export interface Metric {
  /**
   * Unique camelCase name identifying this metric.
   * Used as keys in score results — must be unique within a single `evaluate()` call.
   * Any string is valid; built-in metrics use `faithfulness`, `contextRelevance`, etc.
   */
  readonly name: string

  /** Human-readable description of what this metric measures. */
  readonly description: string

  /**
   * Compute the metric score for one RAG sample.
   *
   * @param input            - The sample's question, answer, contexts, and optional groundTruth.
   * @param provider         - The LLM provider used as the judge for this evaluation.
   * @param includeReasoning - When `true`, include the LLM's reasoning in the output.
   * @returns Promise resolving to a {@link MetricOutput} with score and optional reasoning.
   *          May return `skipped: true` when the metric cannot be computed (e.g. no groundTruth).
   */
  score(
    input: MetricInput,
    provider: LlmProvider,
    includeReasoning?: boolean,
  ): Promise<MetricOutput>
}
